// dummyData.js
export const dummyData = {
  basic_info: {
    name: "John Doe",
    age: 30,
    income: 5500,
    monthly_expenses: 4000,
    total_savings: 25000,
    employment_status: "Employed",
    job_title: "Software Engineer",
    city: "San Francisco",
    currency: "USD",
    monthly_salary_date: "2025-01-01",
  },
  assets: {
    asset_1: {
      type: "Home",
      value: 350000,
      loan_balance: 220000,
    },
    asset_2: {
      type: "Car",
      value: 25000,
      loan_balance: 12000,
    },
  },
  liabilities: {
    liability_1: {
      type: "Student Loan",
      amount: 12000,
      emi: 200,
    },
    liability_2: {
      type: "Car Loan",
      amount: 12000,
      emi: 350,
    },
  },
  profile_score: {
    score: 750,
    last_updated: "2025-01-01",
  },
  spending_data: {
    spending_1: {
      category: "Salary",
      amount: 5500,
      transaction_date: "2025-01-01",
      transaction_type: "Credit",
      account: "Bank Account",
      merchant: "Salary Deposit",
    },
    spending_2: {
      category: "Rent",
      amount: 2000,
      transaction_date: "2025-01-02",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "San Francisco Apartments",
    },
    spending_3: {
      category: "Groceries",
      amount: 150,
      transaction_date: "2025-01-02",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "Trader Joe's",
    },
    spending_4: {
      category: "Dining Out",
      amount: 60,
      transaction_date: "2025-01-03",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "The Cheesecake Factory",
    },
    spending_5: {
      category: "Transportation",
      amount: 75,
      transaction_date: "2025-01-04",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "Uber",
    },
  },
  transactions: {
    transactions_1: {
      category: "Home Loan Payment",
      amount: 2500,
      transaction_date: "2025-01-05",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "Wells Fargo Mortgage",
    },
    transactions_2: {
      category: "Home Loan Payment",
      amount: 30000,
      transaction_date: "2025-01-05",
      transaction_type: "Debit",
      account: "Bank Account",
      merchant: "Wells Fargo Mortgage",
    },
    transactions_3: {
      category: "Home Loan Payment",
      amount: 2500,
      transaction_date: "2025-01-05",
      transaction_type: "Credit",
      account: "Bank Account",
      merchant: "Wells Fargo Mortgage",
    },
    transactions_4: {
      category: "Home Loan Payment",
      amount: 2500,
      transaction_date: "2025-01-05",
      transaction_type: "Credit",
      account: "Bank Account",
      merchant: "Wells Fargo Mortgage",
    },
  },
};
