export const FINANCIAL_CATEGORIES = [
  {
    id: 1,
    name: "Real Estate Master",
    key: "Real_Estate_Master",
    data: {
      basic_info: {
        name: "Alice Johnson",
        age: 32,
        income: 9000,
        monthly_expenses: 6000,
        total_savings: 15000,
        employment_status: "Employed",
        job_title: "Investment Banker",
        city: "New York",
        currency: "USD",
        monthly_salary_date: "2025-01-01",
      },
      assets: {
        asset_1: {
          type: "Stocks",
          value: 200000,
          loan_balance: 0,
        },
        asset_2: {
          type: "Crypto",
          value: 50000,
          loan_balance: 0,
        },
      },
      liabilities: {
        liability_1: {
          type: "Credit Card Debt",
          amount: 15000,
          emi: 500,
        },
      },
      profile_score: {
        score: 20,
        last_updated: "2025-01-01",
      },
      spending_data: {
        spending_1: {
          category: "Stocks Investment",
          amount: 1000,
          transaction_date: "2025-01-02",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Robinhood",
        },
        spending_2: {
          category: "Luxury Dining",
          amount: 300,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Ruth's Chris Steak House",
        },
      },
      transactions: {
        transactions_1: {
          category: "Home Loan Payment",
          amount: 1500,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_2: {
          category: "Home Loan Payment",
          amount: 30000,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_3: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_4: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_5: {
          category: "Home Loan Payment",
          amount: 6500,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
      },
    },
    description: "Become a pro in real estate investments.",
  },
  {
    id: 2,
    name: "Investment Master",
    key: "Investment_Master",
    data: {
      basic_info: {
        name: "Michael Smith",
        age: 28,
        income: 6000,
        monthly_expenses: 2500,
        total_savings: 60000,
        employment_status: "Employed",
        job_title: "Software Engineer",
        city: "Seattle",
        currency: "USD",
        monthly_salary_date: "2025-01-01",
      },
      assets: {
        asset_1: {
          type: "Life Insurance",
          value: 100000,
          loan_balance: 0,
        },
        asset_2: {
          type: "Inheritance",
          value: 200000,
          loan_balance: 0,
        },
      },
      liabilities: {},
      profile_score: {
        score: 50,
        last_updated: "2025-01-01",
      },
      spending_data: {
        spending_1: {
          category: "Savings Deposit",
          amount: 2000,
          transaction_date: "2025-01-03",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "High-Yield Savings Account",
        },
        spending_2: {
          category: "Family Expenses",
          amount: 500,
          transaction_date: "2025-01-04",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Parents' Medical Bills",
        },
      },
      transactions: {
        transactions_1: {
          category: "Home Loan Payment",
          amount: 800,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_2: {
          category: "Home Loan Payment",
          amount: 30000,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_3: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_4: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
      },
    },
    description: "Master the art of stock and crypto investments.",
  },
  {
    id: 3,
    name: "Average Investor",
    key: "Average_Investor",
    data: {
      basic_info: {
        name: "Sophia Lee",
        age: 35,
        income: 7500,
        monthly_expenses: 5500,
        total_savings: 10000,
        employment_status: "Employed",
        job_title: "Product Manager",
        city: "San Francisco",
        currency: "USD",
        monthly_salary_date: "2025-01-01",
      },
      assets: {
        asset_1: {
          type: "Home",
          value: 500000,
          loan_balance: 350000,
        },
        asset_2: {
          type: "Car",
          value: 30000,
          loan_balance: 20000,
        },
      },
      liabilities: {
        liability_1: {
          type: "Home Loan",
          amount: 350000,
          emi: 2500,
        },
        liability_2: {
          type: "Car Loan",
          amount: 20000,
          emi: 500,
        },
      },
      profile_score: {
        score: 80,
        last_updated: "2025-01-01",
      },
      spending_data: {
        spending_1: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        spending_2: {
          category: "Car Loan Payment",
          amount: 500,
          transaction_date: "2025-01-07",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Chase Auto Finance",
        },
      },
      transactions: {
        transactions_1: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_2: {
          category: "Home Loan Payment",
          amount: 30000,
          transaction_date: "2025-01-05",
          transaction_type: "Debit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_3: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
        transactions_4: {
          category: "Home Loan Payment",
          amount: 2500,
          transaction_date: "2025-01-05",
          transaction_type: "Credit",
          account: "Bank Account",
          merchant: "Wells Fargo Mortgage",
        },
      },
    },
    description: "Get started with basic investment strategies.",
  },
];
